/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_OpportunityTest
{
    private static testmethod void testTrigger()
    {
        // Force the dlrs_OpportunityTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        //AK - Commenting this as we have made the dlrs_OpportunityTrigger inactive.
        //dlrs.RollupService.testHandler(new Opportunity());
    }
}